# Generated by Django 3.1.1 on 2020-10-20 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecommerce', '0003_auto_20201018_1240'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carts', '0005_auto_20201017_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=60)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('inprogress', 'In Progress'), ('complete', 'Complete'), ('canceled', 'Canceled')], default='pending', max_length=10)),
                ('billing_name', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('billing_mobile', models.CharField(blank=True, max_length=12, null=True)),
                ('billing_address', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_postcode', models.CharField(blank=True, max_length=6, null=True)),
                ('billing_city', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_state', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_country', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_name', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('shipping_mobile', models.CharField(blank=True, max_length=12, null=True)),
                ('shipping_address', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_postcode', models.CharField(blank=True, max_length=6, null=True)),
                ('shipping_city', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_state', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_country', models.CharField(blank=True, max_length=100, null=True)),
                ('cart', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carts.cart')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.paymentmethod')),
                ('shipping_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.shippingmethod')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
