# Generated by Django 3.1.1 on 2020-10-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='default',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='status',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='default',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
