# Generated by Django 3.1.1 on 2020-10-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20201018_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethod',
            name='charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
    ]
