# Generated by Django 3.1.1 on 2020-10-25 05:53

import consultation.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20201018_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider/', validators=[consultation.validators.validate_file_extension])),
                ('url', models.CharField(blank=True, max_length=200)),
                ('text', models.CharField(blank=True, max_length=150)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
