# Generated by Django 3.1.1 on 2020-12-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20201031_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('mobile', models.IntegerField()),
                ('purpose', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
