# Generated by Django 3.1.1 on 2020-12-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='mobile',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='purpose',
            field=models.CharField(choices=[('General Enquiries', 'General Enquiries'), ('Business Opportunities', 'Business Opportunities'), ('Compliments/Testimonials', 'Compliments/Testimonials'), ('Incomplete Order', 'Incomplete Order'), ('Marketing Opportunities', 'Marketing Opportunities'), ('New Drug/ Product enquiry / New strength', 'New Drug/ Product enquiry / New strength'), ('Order Not Received', 'Order Not Received'), ('Payment Issues', 'Payment Issues'), ('Reward Program', 'Reward Program'), ('Upload Prescription Issues', 'Upload Prescription Issues')], max_length=200),
        ),
    ]
