# Generated by Django 3.1.1 on 2020-12-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_auto_20201227_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='mobile',
            field=models.CharField(max_length=12),
        ),
    ]
