# Generated by Django 3.1.1 on 2021-02-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='zipcode',
            name='days',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
