# Generated by Django 3.1.1 on 2021-02-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_zipcode_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='zipcode',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
