# Generated by Django 3.1.1 on 2021-06-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_auto_20210228_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='charge',
            field=models.FloatField(default=0.0),
        ),
    ]
