# Generated by Django 3.1.1 on 2020-09-13 07:41

import consultation.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=300)),
                ('mobile', models.IntegerField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('marital_status', models.CharField(max_length=10)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('problem', models.TextField()),
                ('history', models.TextField()),
                ('problem_time', models.TextField()),
                ('allergic_problem', models.TextField()),
                ('current_treatment', models.TextField()),
                ('uploaded_files', models.FileField(upload_to='consultation_files/', validators=[consultation.validators.validate_file_extension])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
