# Generated by Django 3.1.1 on 2020-09-13 08:10

import consultation.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='uploaded_files',
        ),
        migrations.CreateModel(
            name='ConsultationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='consultation_files', validators=[consultation.validators.validate_file_extension])),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.consultation')),
            ],
        ),
    ]
