# Generated by Django 3.1.1 on 2020-09-13 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_auto_20200913_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultationimage',
            old_name='file_name',
            new_name='file',
        ),
    ]
