# Generated by Django 3.1.1 on 2020-09-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_auto_20200913_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='gender',
            field=models.CharField(choices=[('', 'Gender'), ('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='marital_status',
            field=models.CharField(choices=[('', 'Marital Status'), ('single', 'Single'), ('married', 'Married')], max_length=10),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='mobile',
            field=models.CharField(max_length=12),
        ),
    ]
