# Generated by Django 3.1.1 on 2020-09-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_auto_20200913_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='treatment_type',
            field=models.CharField(choices=[('', 'Choose Treatment Type'), ('homeopathic', 'Homeopathic'), ('ayurvedic', 'Ayurvedic'), ('unani', 'Unani')], default='unani', max_length=20),
            preserve_default=False,
        ),
    ]
