# Generated by Django 3.1.1 on 2020-09-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0010_auto_20200919_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationresponse',
            name='response_type',
            field=models.CharField(choices=[('answered', 'Answered'), ('rejected', 'Rejected')], default='answered', max_length=10),
        ),
    ]
