# Generated by Django 3.1.1 on 2020-09-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0011_consultationresponse_response_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='height',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('', 'Marital Status'), ('single', 'Single'), ('married', 'Married')], max_length=10),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='weight',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
