# Generated by Django 3.1.1 on 2020-10-10 07:00

import consultation.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0012_auto_20200926_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='allergic_problem',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='current_treatment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='gender',
            field=models.CharField(choices=[('', 'Gender'), ('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='history',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='treatment_type',
            field=models.CharField(choices=[('', 'Choose Treatment Type'), ('homeopathic', 'HOMEOPATHY'), ('ayurvedic', 'AYURVEDA'), ('unani', 'UNANI'), ('diet_nutritions', 'DIET & NUTRITIONS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='weight',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='consultationimage',
            name='file',
            field=models.FileField(blank=True, upload_to='static/consultation_files/', validators=[consultation.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('', 'Choose Treatment Type'), ('homeopathic', 'HOMEOPATHY'), ('ayurvedic', 'AYURVEDA'), ('unani', 'UNANI'), ('diet_nutritions', 'DIET & NUTRITIONS')], max_length=30),
        ),
    ]
