# Generated by Django 3.1.1 on 2020-10-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0015_city_country_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='billing_mobile',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
