# Generated by Django 3.1.1 on 2020-10-10 07:17

from django.db import migrations, models
import products.validators


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201010_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, upload_to='category_images/', validators=[products.validators.image_extension]),
        ),
    ]
