# Generated by Django 3.1.1 on 2020-10-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201010_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='product', max_length=300, unique=True),
        ),
    ]
