# Generated by Django 3.1.1 on 2020-10-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
