# Generated by Django 3.1.1 on 2020-12-22 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20201031_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uses', models.TextField(blank=True)),
                ('warnings', models.TextField(blank=True)),
                ('interactions', models.TextField(blank=True)),
                ('directions', models.TextField(blank=True)),
                ('side_effects', models.TextField(blank=True)),
                ('more_information', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
