# Generated by Django 3.1 on 2021-02-06 07:50

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210126_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttab',
            name='directions',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='producttab',
            name='interactions',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='producttab',
            name='more_information',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='producttab',
            name='side_effects',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='producttab',
            name='uses',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='producttab',
            name='warnings',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
