# Generated by Django 3.1.1 on 2020-10-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_auto_20201024_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
